### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by ZucchiniZe** [Edmeral/nodecup#2]
I was wondering what terminal emulator you used in the screenshots, it looks really nice and I was wanting to get it if I could.

**Comment by Edmeral** [comment]
It is simply the default terminal app on Ubuntu Gnome + using this [theme](http://satya164.deviantart.com/art/Numix-GTK3-theme-360223962)

**Comment by ZucchiniZe** [comment]
Thanks!

**Comment by Edmeral** [comment]
;-)
